version: '3.7'
services:
  web:
      container_name: hui01
      build: .
      ports:
      - "5000:5000"
      #volumes:
      # .:/app # 把當前資料夾 mount 掛載進去 container，這樣你可以直接在本地端專案資料夾改動檔案，container 裡面的檔案也會更動也不用重新 build image！
  redis:
      image: "redis:alpine" # 從 Docker Hub registry 來的 image